Feature/project setup
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-A pull request #12
Opened 2024-10-16 13:53 UTC by teasmade

## Initialise project, setup base dependencies, add code quality tools

- Init root project
- Init `/app` with Vite - TS
- Init `/api` with ts-node-dev and test script
- Add eslint and prettier configurations to `/api` and `/client`
- Init husky and lint-staged, setup to run eslint and prettier checks in pre-commit

2024-10-16 14:05 UTC, PierreDelarocque approved these changes, later dismissed

2024-10-17 06:54 UTC, Gadln approved these changes, later dismissed

2024-10-17 07:58 UTC, jujuck requested changes

2024-10-17 07:58 UTC, jujuck commented on api/src/test.ts
> +console.info("Node works");
A supprimer

2024-10-17 08:11 UTC, teasmade commented on api/src/test.ts
> +console.info("Node works");
Done

2024-10-17 08:13 UTC, jujuck approved these changes

2024-10-17 08:13 UTC, merged