Feature/page creat character stats
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-A pull request #27
Opened 2024-10-25 10:03 UTC by Adri-bis

- Ajout de la page de création de personnage.

- Ajout d'un tableau de stats.

- Ajout de deux inputs : prénom et choisir sa ville.

- Ajout d'un bouton pour naviguer.

2024-10-25 10:06 UTC, julien44830 commented on client/src/components/competitor/StatsCharacter.tsx
> +      <div className="B m-6 w-full min-w-[280px] rounded-xl bg-blue-fd bg-opacity-85 p-2 md:mr-24 md:w-[400px]">
utiliser <section> ?

2024-10-25 10:18 UTC, julien44830 requested changes
les noms de variables doivent être en anglais et tu peux utiliser des balise autre que div à 2 endroit

2024-10-25 10:18 UTC, julien44830 commented on client/src/components/competitor/StatsCharacter.tsx
> +        aria-label="Start the game"
`aria-label="Start the game"`

traduire en :
`aria-label="Commencer le jeu"`

2024-10-25 10:18 UTC, julien44830 commented on client/src/pages/CreatCharacterPage.tsx
> +  const [prenom, setPrenom] = useState("");
state à déclarer en anglais 
`const [prenom, setPrenom] = useState("");`
en
`const [name, setName] = useState("");`

2024-10-25 10:18 UTC, julien44830 commented on client/src/pages/CreatCharacterPage.tsx
> +    setPrenom(e.target.value);
`setPrenom(e.target.value);`=`setName(e.target.value);`

2024-10-25 10:18 UTC, julien44830 commented on client/src/pages/CreatCharacterPage.tsx
> +              value={prenom}
`value={prenom}`=`value={name}`

2024-10-25 10:18 UTC, julien44830 commented on client/src/pages/CreatCharacterPage.tsx
> +    <div className="-mt-60 h-full w-full p-8 backdrop-blur md:-mt-40 lg:-mt-24">
` <div className="-mt-60 h-full w-full p-8 backdrop-blur md:-mt-40 lg:-mt-24">` 
Utiliser une balise `<section>` ?
` <section className="-mt-60 h-full w-full p-8 backdrop-blur md:-mt-40 lg:-mt-24">`

2024-10-25 10:33 UTC, julien44830 submitted a review, later dismissed

2024-10-25 13:42 UTC, PierreDelarocque approved these changes, later dismissed

2024-10-25 13:45 UTC, teasmade commented on client/src/pages/CreatCharacterPage.tsx
Nom de fichier plutôt `CreateCharacterPage.tsx`

2024-10-25 15:05 UTC, teasmade commented on client/src/pages/CreateCharacterPage.tsx
> +            <select className="text-withe select w-full max-w-xs bg-transparent focus:bg-white focus:text-black">
Est-ce que `text-withe` est une vraie classe?

2024-10-28 16:21 UTC, teasmade approved these changes, later dismissed

2024-10-28 16:21 UTC, teasmade commented on client/src/pages/CreateCharacterPage.tsx
> +          <div className="B flex flex-col items-center p-4">
classe B?

2024-10-30 08:10 UTC, julien44830 approved these changes, later dismissed

2024-10-30 08:15 UTC, Gadln submitted a review, later dismissed

2024-10-30 08:19 UTC, jujuck requested changes

2024-10-30 08:19 UTC, jujuck commented on client/src/pages/CreateCharacterPage.tsx
> +        <div className="grid w-full grid-cols-2 gap-4 py-4">
Remplacer une div par form

2024-10-30 08:19 UTC, jujuck commented on client/src/pages/HomePage.tsx
> +          to="/create"
Normalement, on ne met pas de verbe dans une URL, plutot creation ou initialisation

2024-10-30 08:19 UTC, jujuck commented on client/src/pages/CreateCharacterPage.tsx
> +
Ligne morte

2024-10-30 08:19 UTC, jujuck commented on client/src/components/competitor/StatsCharacter.tsx
> +  const stats = [
A mettre en dehors de la fonction

2024-10-30 08:42 UTC, PierreDelarocque approved these changes, later dismissed

2024-10-30 08:43 UTC, julien44830 approved these changes, later dismissed

2024-10-30 09:16 UTC, julien44830 approved these changes

2024-10-30 09:17 UTC, jujuck approved these changes

2024-10-30 09:17 UTC, merged