Feature/carousel avatar
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-A pull request #35
Opened 2024-10-31 12:30 UTC by Adri-bis

- Création du carrousel d'avatars

- Responsive mobile

- Harmonisation du CSS pour une meilleure lisibilité

- Amélioration de la sémantique HTML en utilisant des balises adaptées

![Capture d'écran 2024-10-31 132559](https://github.com/user-attachments/assets/d2108137-3f47-442f-8eb3-ca0b052bab01)
![Capture d'écran 2024-10-31 132613](https://github.com/user-attachments/assets/09980dab-d38e-46c9-bdf5-4a223f5ad512)

2024-10-31 13:09 UTC, julien44830 approved these changes, later dismissed

2024-10-31 13:11 UTC, PierreDelarocque submitted a review, later dismissed

2024-10-31 13:16 UTC, julien44830 submitted a review, later dismissed

2024-10-31 13:18 UTC, Gadln approved these changes

2024-10-31 13:41 UTC, jujuck requested changes
Un peu de refacto pour améliorer la maintenance

2024-10-31 13:41 UTC, jujuck commented on client/src/components/competitor/AvatarCarouselMobile.tsx
> +                <figure
A mettre dans un composant unique entre la version desktop et mobile avec une ou plusieurs props de mise en forme

2024-10-31 13:41 UTC, jujuck commented on client/src/components/competitor/AvatarCarouselDesktop.tsx
> +                <figure
A mettre dans un composant unique entre la version desktop et mobile avec une ou plusieurs props de mise en forme

2024-10-31 13:41 UTC, jujuck commented on client/src/components/competitor/AvatarCarouselDesktop.tsx
> +  const handleTouchStart = (e: React.TouchEvent) => {
Passer la logique de swipe vers le parent pour garder une unicité entre le mobile et le desktop

2024-11-01 15:55 UTC, Gadln approved these changes, later dismissed

2024-11-05 15:11 UTC, julien44830 commented on client/src/components/CarouselWrapper.tsx
> +  const handleDragMove = (diff: number) => {
saut de ligne

2024-11-05 15:14 UTC, julien44830 commented on client/src/components/CarouselWrapper.tsx
> +    if (diff > numberPx) {
saut de ligne

2024-11-05 15:18 UTC, Gadln approved these changes

2024-11-05 15:20 UTC, julien44830 approved these changes

2024-11-05 16:10 UTC, jujuck approved these changes

2024-11-05 16:10 UTC, merged