Feature/page start trial
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-A pull request #36
Opened 2024-10-31 13:59 UTC by julien44830

![Capture d'écran 2024-10-31 145359](https://github.com/user-attachments/assets/51b31ea1-099f-400e-82da-34a4c172dd7f)

- Création de la page épreuve (StartTrialPage.tsx)
- Création de la modale de résulta de l'épreuve (ModaleResultaTrial.tsx)
- La modale s'affiche au click du bouton "démarrer l'épreuve
- La modale change dynamiquement en fonction du résulta (victoire / défaite)
- L'avatar du perdant est grisé

2024-10-31 14:04 UTC, Adri-bis requested changes

2024-10-31 14:04 UTC, Adri-bis commented on client/src/components/trial/ModaleResultTrial.tsx
> +
espace mort

2024-10-31 14:04 UTC, Adri-bis commented on client/src/components/trial/ModaleResultTrial.tsx
> +
espace mort

2024-10-31 14:36 UTC, PierreDelarocque submitted a review, later dismissed

2024-10-31 14:36 UTC, Gadln approved these changes, later dismissed

2024-10-31 15:33 UTC, jujuck requested changes

2024-10-31 15:33 UTC, jujuck commented on client/src/components/trial/ModaleResultTrial.tsx
> +      <section
Modification faite

2024-10-31 15:33 UTC, jujuck commented on client/src/pages/StartTrialPage.tsx
> +const resultTrial: { [key: string]: { status: string } } = {
ON remplace par un const resultTrial = ["DEFAITE", "VICTOIRE"]

2024-10-31 15:33 UTC, jujuck commented on client/src/pages/StartTrialPage.tsx
> +    if (resultTrial.victoire.status === "VICTOIRE") {
setResult(resultTrial[Math.ceil(Math.random() * 2))])

2024-10-31 15:47 UTC, Adri-bis submitted a review, later dismissed

2024-10-31 15:48 UTC, PierreDelarocque submitted a review, later dismissed

2024-10-31 15:57 UTC, jujuck requested changes

2024-10-31 15:57 UTC, jujuck commented on client/src/pages/StartTrialPage.tsx
> +      <button
button type="button"

2024-10-31 15:57 UTC, jujuck commented on client/src/pages/StartTrialPage.tsx
> +  const checkResulta = () => {
Renommage de la fonction avec un "t" à la fin

2024-11-01 11:32 UTC, Gadln commented on client/src/pages/StartTrialPage.tsx
> +      <button
ligne 4 récupérer un seul c
ligne 6 il manque un e à course
ligne 18 les informationS et résultaT (idem ligne 68 et 70)

2024-11-01 15:55 UTC, Gadln submitted a review, later dismissed

2024-11-01 15:58 UTC, julien44830 commented
utilisation de git pull --force pour fusionner 2 commit en 1 avec la commande git rebase -i HEAD~2

2024-11-04 07:52 UTC, Adri-bis approved these changes, later dismissed

2024-11-04 20:22 UTC, Gadln submitted a review, later dismissed

2024-11-05 10:55 UTC, jujuck requested changes

2024-11-05 10:55 UTC, jujuck commented on client/src/components/trial/ModaleResultTrial.tsx
> +            src="./img/competitors/avatars/avatar.png"
Uniformise tes path de chemin entre tes images en relatif ou absolue. Tu adoptes plusieurs approches dans ta page

2024-11-05 13:33 UTC, Adri-bis approved these changes

2024-11-05 14:20 UTC, PierreDelarocque approved these changes

2024-11-05 14:25 UTC, Gadln approved these changes

2024-11-05 15:13 UTC, jujuck approved these changes

2024-11-05 15:13 UTC, merged