Feature/carousel god
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-A pull request #39
Opened 2024-11-06 11:20 UTC by PierreDelarocque

add a carousel god for the choosegod page

2024-11-06 11:27 UTC, julien44830 commented on client/src/pages/ChooseGodPage.tsx
saut de ligne inutil

2024-11-06 11:29 UTC, julien44830 approved these changes, later dismissed

2024-11-06 11:29 UTC, Adri-bis approved these changes, later dismissed

2024-11-06 12:49 UTC, jujuck requested changes

2024-11-06 12:49 UTC, jujuck commented on client/src/pages/CreateCharacterPage.tsx
> +      <AvatarCarouselWrapper imageUrls={imageUrls} myTitle={myTitle} />
Ecris directement le texte du titre au moment du passage de props. Pas besoin de créer des variables qui n'ont ni dynamisme, ni réutilisation

2024-11-06 12:49 UTC, jujuck commented on client/src/pages/ChooseGodPage.tsx
> +        <AvatarCarouselWrapper imageUrls={imageUrls} myTitle={myTitle} />
Ecris directement le texte du titre au moment du passage de props. Pas besoin de créer des variables qui n'ont ni dynamisme, ni réutilisation

2024-11-06 12:49 UTC, jujuck commented on client/src/pages/ChooseGodPage.tsx
> +  const imageUrls = [
Passer en données dynamqiue du back end... via un filtre
En profiter pour mettre à jour l'autre carroussel

2024-11-06 16:22 UTC, Gadln approved these changes

2024-11-06 16:55 UTC, julien44830 commented on client/src/pages/CreateCharacterPage.tsx
> +  /* const { data, loading, error } = useGetImageFiltreQuery({
Pourquoi les commentaire ?
En attente préparation du back ?
```
  /* const { data, loading, error } = useGetImageFiltreQuery({
    variables: { type: "competitor_avatar" },
  });*/

  // if (loading) return <p>Loading...</p>;
  //if (error) return <p>Error: {error.message}</p>;
  // console.log("ma data image", data);
  // const imageUrls = data;```

2024-11-06 16:57 UTC, julien44830 approved these changes, later dismissed
tu as des commentaires dans le fichier : `CreateCharacterPage.tsx`

Pourquoi ?

2024-11-07 07:57 UTC, Gadln approved these changes, later dismissed

2024-11-07 10:55 UTC, Gadln commented on client/src/pages/ChooseGodPage.tsx
l.46  remplacer ? par && et supprimer l.58-59 ?

2024-11-07 10:58 UTC, Gadln commented on client/src/pages/CreateCharacterPage.tsx
mettre des villes grecques en dure ?

2024-11-07 11:03 UTC, julien44830 submitted a review, later dismissed

2024-11-07 11:03 UTC, julien44830 commented on client/src/pages/CreateCharacterPage.tsx
Vas être fait sur une autre PR

2024-11-07 11:05 UTC, Gadln submitted a review, later dismissed

2024-11-07 11:26 UTC, Gadln approved these changes

2024-11-07 11:28 UTC, julien44830 approved these changes

2024-11-07 13:04 UTC, jujuck approved these changes

2024-11-07 13:05 UTC, merged