Feature/stats details
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-A pull request #43
Opened 2024-11-07 17:01 UTC by teasmade

Adds pages with full combat results accessible from the statistics page.
Fixes regression on various entity relations in #42

2024-11-07 17:43 UTC, julien44830 requested changes
tu as un commentaire je suis pas sur qu'il soit utile

2024-11-07 17:43 UTC, julien44830 commented on client/src/pages/StatisticsDetailPage.tsx
> +// }
a quoi sert ce commentaire, cette fonction servira telle ?
```
// function formatCombatDate(date: string) {
//   return new Date(date).toLocaleDateString("fr-FR", {
//     year: "numeric",
//     month: "long",
//     day: "numeric",
//   });
// }
```

2024-11-08 08:28 UTC, Adri-bis approved these changes, later dismissed

2024-11-08 08:28 UTC, PierreDelarocque submitted a review, later dismissed

2024-11-08 08:29 UTC, julien44830 approved these changes, later dismissed

2024-11-08 08:44 UTC, jujuck requested changes

2024-11-08 08:44 UTC, jujuck commented on api/src/combat/combat.resolver.ts
> +  @Query(() => CombatResult)
A simplifier par l'appel à des fonctions externes à celle ci

2024-11-08 09:10 UTC, PierreDelarocque approved these changes

2024-11-08 09:10 UTC, julien44830 approved these changes

2024-11-08 09:54 UTC, jujuck approved these changes

2024-11-08 09:54 UTC, merged